"""Services against a real database.

The unit tests in tests/unit/ already proved these services make the right
DECISIONS. These prove the decisions survive contact with PostgreSQL - that
the commit really commits, that the soft delete is really persisted, that the
values the database generates arrive back in Python.

That distinction is worth holding on to. A fake repository can be wrong in the
same direction as the service, and then both agree and both are broken. This
layer is where that gets caught.
"""

from __future__ import annotations

import uuid

import pytest
from sqlalchemy import select

from app.core.enums import UserRole
from app.core.exceptions import EmailAlreadyExists, InvalidToken, UserNotFound
from app.core.security import verify_password
from app.db.models.user import User

pytestmark = [pytest.mark.integration, pytest.mark.db]

PASSWORD = "Password123!"


# ------------------------------------------------------------------- writes


def test_register_really_persists_a_row(auth_service, db_session):
    user = auth_service.register(
        email="persisted@example.com",
        full_name="Persisted",
        phone=None,
        password=PASSWORD,
    )

    stored = db_session.scalar(select(User).where(User.id == user.id))
    assert stored is not None
    assert stored.public_id is not None  # generated by Postgres
    assert verify_password(PASSWORD, stored.hashed_password)


def test_soft_delete_leaves_the_row_in_place(user_service, make_user, db_session):
    """"Delete" here means "set deleted_at". The row must still exist - users
    own projects with ON DELETE RESTRICT, so a hard delete would fail anyway,
    and an audit trail with holes in it is not an audit trail."""
    user = make_user(email="soft@example.com")

    user_service.soft_delete(user, user.public_id)

    row = db_session.scalar(select(User).where(User.id == user.id))
    assert row is not None
    assert row.deleted_at is not None


def test_the_updated_at_trigger_overwrites_whatever_the_client_sent(
    user_service, make_user, db_session
):
    """updated_at has no Python-side onupdate: a Postgres trigger owns it, so
    the column is correct no matter who writes the row - the API, a script, or
    someone in psql.

    Two things worth knowing, both learned the hard way writing this test:

    1. It only passes because the test schema is built by the migrations. The
       trigger is hand-written SQL in the baseline migration and does not exist
       in the ORM models, so Base.metadata.create_all() would not create it.

    2. You cannot check `updated_at > before` here. The trigger calls now(),
       which in PostgreSQL returns the TRANSACTION's start time, not the wall
       clock - and this whole test runs inside one transaction, so every now()
       returns the same instant. Instead the test back-dates the row and checks
       the trigger overwrote it, which is the behaviour that actually matters.
    """
    from sqlalchemy import text

    user = make_user(email="touch@example.com")

    # Try to back-date the row by hand, the way a careless script might.
    db_session.execute(
        text("UPDATE users SET updated_at = '2020-01-01T00:00:00Z' WHERE id = :i"),
        {"i": user.id},
    )
    db_session.commit()
    db_session.refresh(user)

    assert user.updated_at.year != 2020  # the trigger overwrote it with now()

    # And the same holds for an ORM write through the service.
    user_service.update(user, user.public_id, {"full_name": "Touched"})
    assert user.updated_at.year != 2020


def test_a_conflicting_email_is_refused_before_anything_is_written(
    user_service, make_user, db_session
):
    make_user(email="taken@example.com")
    mine = make_user(email="mine@example.com")

    with pytest.raises(EmailAlreadyExists):
        user_service.update(mine, mine.public_id, {"email": "taken@example.com"})

    db_session.rollback()
    assert db_session.scalar(select(User.email).where(User.id == mine.id)) == (
        "mine@example.com"
    )


def test_restore_round_trip(user_service, make_user, db_session):
    user = make_user(email="round@example.com")
    user_service.soft_delete(user, user.public_id)

    with pytest.raises(UserNotFound):
        user_service.get(user.public_id)  # invisible while deleted

    restored = user_service.restore(user.public_id)

    assert restored.deleted_at is None
    assert user_service.get(user.public_id).id == user.id


# ------------------------------------------------------ auth across a commit


def test_logout_invalidates_a_token_that_worked_a_moment_ago(
    auth_service, make_user
):
    """Revocation, end to end, through the database: the token_version bump is
    committed and the next token check reads the new value."""
    user = make_user(email="revoke@example.com")
    pair = auth_service.login("revoke@example.com", PASSWORD)

    assert auth_service.user_from_access_token(pair.access_token).id == user.id

    auth_service.logout(user)

    with pytest.raises(InvalidToken):
        auth_service.user_from_access_token(pair.access_token)


def test_changing_your_password_logs_every_session_out(auth_service, make_user):
    user = make_user(email="pw@example.com")
    pair = auth_service.login("pw@example.com", PASSWORD)

    auth_service.change_password(user, current=PASSWORD, new="NewPassword1!")

    with pytest.raises(InvalidToken):
        auth_service.user_from_access_token(pair.access_token)
    # ...and the new password works
    auth_service.login("pw@example.com", "NewPassword1!")


def test_deleting_a_user_kills_their_token(user_service, auth_service, make_user):
    user = make_user(email="deleted@example.com")
    pair = auth_service.login("deleted@example.com", PASSWORD)

    user_service.soft_delete(user, user.public_id)

    with pytest.raises(InvalidToken):
        auth_service.user_from_access_token(pair.access_token)


def test_a_promoted_user_gets_their_new_role_immediately(
    user_service, auth_service, make_user
):
    """The role is read from the row on every request, never from a token
    claim. That is what makes "revoke admin" take effect at once instead of
    whenever the old token happens to expire."""
    admin = make_user(email="admin@example.com", role=UserRole.ADMIN)
    target = make_user(email="target@example.com")

    user_service.set_role(admin, target.public_id, UserRole.ADMIN)

    fresh = auth_service.users.get_by_public_id(target.public_id)
    assert fresh.role is UserRole.ADMIN


# ------------------------------------------------------------ the race case


def test_two_registrations_of_the_same_email_cannot_both_win(
    auth_service, db_session
):
    """The check-then-insert race, made deterministic.

    AuthService.register asks "is this email taken?" and then inserts. Two
    requests can both get "no" before either inserts. The service cannot
    prevent that on its own - only the unique index can, which is why
    app/api/errors.py has an IntegrityError handler that returns 409.

    Simulated here by inserting the competing row between the two steps.
    """
    from sqlalchemy.exc import IntegrityError

    auth_service.register(
        email="race@example.com", full_name="First", phone=None, password=PASSWORD
    )

    db_session.add(
        User(
            email="race@example.com",
            full_name="Second",
            hashed_password="x",
            role=UserRole.USER,
        )
    )

    with pytest.raises(IntegrityError):
        db_session.flush()
    db_session.rollback()


def test_get_with_a_random_uuid_is_a_clean_not_found(user_service):
    with pytest.raises(UserNotFound):
        user_service.get(uuid.uuid4())
