"""baseline schema from day 3 and 4

This migration is the one hand exception to "migrations only add, never
recreate history": it exists to bring an already-hand-built Day 3 database
under Alembic's control, so from here on every change to `tasks`,
`projects`, etc. goes through a migration instead of a manual `psql`
session.

Everything below `# ### end Alembic commands ###` was NOT autogenerated -
autogenerate only sees what SQLAlchemy's Table/Column objects describe, so
it never produces CHECK constraints coming from a plain `Enum(...,
create_constraint=False)`, partial indexes, trigger functions, or views.
Those are exactly the DB-side pieces `models.py` deliberately leaves out
(see the comments in `Task.status` and `TimestampMixin`), so they're added
here by hand with `op.execute()` / `op.create_check_constraint()`.

Revision ID: 0f4f2ddf22f3
Revises: 
Create Date: 2026-08-13 09:13:48.278995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4f2ddf22f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'done', name='taskstatus', native_enum=False, length=20), server_default=sa.text("'todo'"), nullable=False),
    sa.Column('priority', sa.SmallInteger(), server_default=sa.text('3'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_tags',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id')
    )
    # ### end Alembic commands ###

    # --- everything past this point is hand-written, see the module docstring ---

    # CHECK constraints: `Task.status` uses create_constraint=False (a plain
    # TEXT column on the SQLAlchemy side) specifically so the DB, not the
    # ORM, is the source of truth here - see run_day3.py's q6_constraints,
    # which expects Postgres itself to reject a bad status.
    op.create_check_constraint(
        "ck_tasks_status_valid",
        "tasks",
        "status in ('todo', 'in_progress', 'done')",
    )
    op.create_check_constraint(
        "ck_tasks_title_not_blank",
        "tasks",
        "length(trim(title)) > 0",
    )

    # Partial unique index: only ONE active (non-soft-deleted) user may hold
    # a given email. A deleted user's old email is free to be reused.
    op.create_index(
        "ux_users_email_active",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # Composite index backing the "tasks for a project, filtered by status"
    # query - see run_day3.py's q8_explain, which checks the planner picks
    # this up instead of a sequential scan.
    op.create_index("idx_tasks_project_status", "tasks", ["project_id", "status"])

    # updated_at trigger: the ORM's TimestampMixin intentionally has no
    # Python-side onupdate for updated_at - this function is what actually
    # maintains it, on every UPDATE, regardless of which client wrote the
    # row (ORM, psql, another service).
    op.execute(
        """
        CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("users", "projects", "tasks"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
            """
        )

    # Convenience views for the common "ignore soft-deleted rows" case.
    op.execute("CREATE VIEW active_users AS SELECT * FROM users WHERE deleted_at IS NULL;")
    op.execute("CREATE VIEW active_projects AS SELECT * FROM projects WHERE deleted_at IS NULL;")
    op.execute("CREATE VIEW active_tasks AS SELECT * FROM tasks WHERE deleted_at IS NULL;")


def downgrade() -> None:
    """Downgrade schema."""
    # Reverse of upgrade(): views and triggers depend on the tables, so they
    # have to go first, or DROP TABLE below fails with a dependency error.
    op.execute("DROP VIEW IF EXISTS active_tasks;")
    op.execute("DROP VIEW IF EXISTS active_projects;")
    op.execute("DROP VIEW IF EXISTS active_users;")

    for table in ("tasks", "projects", "users"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table};")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tags')
    op.drop_table('task_history')
    op.drop_table('tasks')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
